Add github actions test, move functions

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -16,4 +16,20 @@ jobs:
       - name: Test with Valgrind
         run: |
           sudo apt-get install valgrind
-          valgrind --error-exitcode=1 ./file.out ./kbc.c enc cbc ./kes.c.bin "AAAA" "BBBB"
+          valgrind --error-exitcode=1 ./file.out ./kbc.c enc cbc ./kbc.c.bin "AAAA" "BBBB"
+      
+      - name: Decrypt Test
+        run: |
+          echo "This is a top secret message for KBC!" > original.txt
+          ./file.out ./original.txt enc cbc ./middle.kbc "AAAA" "BBBB"
+          ./file.out ./middle.kbc dec cbc ./decrypt.txt "AAAA" "BBBB"
+
+          ORIG_HASH=$(sha256sum original.txt | awk '{ print $1 }')
+          DECR_HASH=$(sha256sum decrypt.txt | awk '{ print $1 }')
+          if [ "$ORIG_HASH" == "$DECR_HASH" ]; then
+            echo "Enc-Dec Test Passed"
+          else
+            echo "Enc-Dec Test Failed"
+            exit 1
+          fi
+      
